name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6.0.3
              
            - name: Welcome
              run: echo "welcome"
            - name: What do you want?
              run: echo "What do you want?"
            - name: List Files
              run: ls
            - name: Present Directory
              run: pwd
            - name: List Files
              run: cat README.md